### ISSUE TITLE
Cannot use service labels .?

### ISSUE THREAD

**Issue by iangregsondev** [acouvreur/traefik-ondemand-plugin#3]
Hi,

Impressive plugin.

Can you clarify this

Cannot use service labels

I normally attach traefik labels under deploy of a compose file for swarm.

These hold the domain name and service port etc. these are still supported right ?

**Comment by acouvreur** [comment]
When a service is scaled to zero, the labels are not registered anymore. The route is no longer reachable and thus the plugin cannot be triggered.

The only way to scale to zero is to have the configuration under the file provider. Which is now independant from the service's lifecycle. It can be scaled to zero, the route will still be triggered.

So you cannot use the labels on your docker-compose file because of this. Is this the answer you expected ?

**Comment by iangregsondev** [comment]
Ok thanks @acouvreur . Yes this is the answer i was expecting, I just wanted to confirm it.

**Comment by acouvreur** [comment]
You can actually use `- traefik.docker.lbswarm=true`.
If you do not use the swarm load balancer, traefik will evict the service from its pool as soon as the service is 0/0. If you do not set that, fallback to dynamic-config.yml file usage.
